apiVersion: v2
name: scalarflow-web
description: A Helm chart for ScalarFlow Web - Frontend web application
type: application
version: "0.1.0"
appVersion: "SNAPSHOT"
kubeVersion: ">=1.19.0-0"
home: https://github.com/scalar-labs/scalarflow-helm-charts
sources:
  - https://github.com/scalar-labs/scalarflow-helm-charts
