apiVersion: v2
name: scalarflow-api
description: A Helm chart for ScalarFlow API - Backend REST API service
type: application
version: "0.3.0"
appVersion: "SNAPSHOT"
kubeVersion: ">=1.19.0-0"
home: https://github.com/scalar-labs/scalarflow-helm-charts
sources:
  - https://github.com/scalar-labs/scalarflow-helm-charts
